### ISSUE TITLE
bytom 测试案例 不通过

### ISSUE THREAD

**Issue by MacOMNI** [blocktree/go-owcdrivers#25]
bytom 测试案例都校验失败, 源代码下载直接运行的,是我遗漏了什么嘛,pubkey is 0000...?

**Comment by heshuchao** [comment]
这个问题是底层库版本更迭的时候，曲线类型命名改动导致的。
如果需要验证通过单签交易，可以把这个文件[bytomTransaction/sigPub.go](https://github.com/blocktree/go-owcdrivers/blob/master/bytomTransaction/sigPub.go)的第47行改为：
`pub := owcrypt.Point_mulBaseG(prikey, owcrypt.ECC_CURVE_ED25519)`

**Comment by heshuchao** [comment]
[bytomTransaction/transaction_test.go](https://github.com/blocktree/go-owcdrivers/blob/master/bytomTransaction/transaction_test.go)里面的测试案例Test_case4，将公钥生成的曲线类型指定为owcrypt.ECC_CURVE_ED25519即可通过测试。

即，将该文件的239和240行修改为：
`	pubkey1 := owcrypt.Point_mulBaseG(prikey1, owcrypt.ECC_CURVE_ED25519)`
`	pubkey2 := owcrypt.Point_mulBaseG(prikey2, owcrypt.ECC_CURVE_ED25519)`

**Comment by MacOMNI** [comment]
感谢分享

**Comment by MacOMNI** [comment]
我最近也在搞 多币种 wallet 开发,MacKunsj 这是我微信号,我们交个朋友吧,决战到天亮呐

**Comment by Jinxiansen** [comment]
@MacOMNI   😗大佬多多指教！
