### ISSUE TITLE
尝试用 bytom 构造一笔交易

### ISSUE THREAD

**Issue by MacOMNI** [blocktree/go-owcdrivers#27]
尝试 构造了一笔交易,但使用官网但使用官网的 extendPrivteKey 构建交易 看起来是不成功
![1573034408040](https://user-images.githubusercontent.com/6373598/68289220-b5adab80-00c0-11ea-8b1b-8b4935e4951d.jpg)
这里bytom逻辑 是脱离 官网的思路,直接利用公私钥 转换的地址做的交易流程吧

**Comment by heshuchao** [comment]
官方私钥 -> SHA512 -> (摘要结果) -> 左边32字节 || 右边32字节 

其中 左边32字节是 go-owcdrivers的私钥

这么做是为了适配密钥扩展
